import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "./ui/font";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
